spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/assets_center?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    username: root
    password: 199011081108
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      max-idle: 20
      min-idle: 5
    platform: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 300
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
logging:
  level:
    org:
      hibernate:
        SQL: debug